services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timeseriesdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: timeseriesdb
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    restart: unless-stopped
